<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

In [2]:
import numpy as np

In [3]:
my_arr = np.arange(1000000)

my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 37 ms


In [5]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.88 s


<strong class='alert alert-info' > Random data generator   </strong>


<table class="table table-hover">
	<thead>
		<tr>
			<th> random </th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>data</td>
		</tr>
	</tbody>
</table>



In [6]:
data = np.random.randn(3,4)

data

array([[ 1.07423452, -0.1169648 , -0.6862547 , -0.42338855],
       [ 2.62835027, -1.00715032,  0.42791645,  0.48766058],
       [-0.23297749, -1.38548472, -0.68313798, -1.08674184]])

In [7]:
data * 3

array([[ 3.22270355, -0.35089439, -2.05876411, -1.27016564],
       [ 7.88505081, -3.02145097,  1.28374936,  1.46298175],
       [-0.69893247, -4.15645417, -2.04941395, -3.26022551]])

In [8]:
data + data

array([[ 2.14846904, -0.23392959, -1.3725094 , -0.84677709],
       [ 5.25670054, -2.01430065,  0.85583291,  0.97532117],
       [-0.46595498, -2.77096945, -1.36627597, -2.17348367]])

### describe the shape of the array 
data.shape


In [9]:
## describe the shape of the array 
data.shape



(3, 4)

### data type 
data.dtype

In [10]:
data.dtype


dtype('float64')

### simple array to numpy array

In [11]:
list1 = [1, 2, 3.4 ,53]

arr1 = np.array(list1)
arr1


array([ 1. ,  2. ,  3.4, 53. ])

## Two dim Array


In [12]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

arr2 = np.array(data2)
arr2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## to check dimension

arr.ndim


In [13]:
arr2.ndim



2

## to generate zeros 

np.zeros()

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.identity(3)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## define datatype
arr.astype


In [27]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype
float_type = arr.astype(np.float64)



In [28]:
float_type.dtype


dtype('float64')

In [30]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.dtype


dtype('float64')

In [32]:
int_type = arr.astype(np.int16)
int_type.dtype
int_type

array([ 3, -1, -2,  0, 12, 10], dtype=int16)

In [35]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
string = np.array(['hi', 'ge'])


In [37]:
string.dtype

dtype('<U2')

In [38]:
numeric_strings
numeric_strings.dtype

dtype('S4')

In [40]:
new_float = numeric_strings.astype(float)
new_float


array([ 1.25, -9.6 , 42.  ])

In [41]:
new_float.dtype


dtype('float64')

In [42]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [44]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [45]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [46]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [47]:
arr > arr2

array([[ True, False,  True],
       [False,  True, False]])

## Basic Indexing and Slicing



In [48]:
arr = np.arange(10)


In [49]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr[5]

5

In [51]:
arr[5:8]

array([5, 6, 7])

In [52]:
arr[5:8] =12

In [53]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [54]:
arr_slice = arr[5:8]

In [55]:
arr_slice

array([12, 12, 12])

In [56]:
arr_slice[1] = 1234

In [57]:
arr

array([   0,    1,    2,    3,    4,   12, 1234,   12,    8,    9])

In [58]:
arr_slice[:] = 64

In [59]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [60]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [61]:
arr2d[2]

array([7, 8, 9])

In [62]:
arr2d[0][2]

3

In [63]:
arr2d[0,2]

3

In [64]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [65]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [66]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
old_value = arr3d[0].copy()

In [68]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [69]:
arr3d[0] = old_value
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [70]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
arr2d[:2, :2]

arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [75]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
arr2d[1, :2]


array([4, 5])

In [77]:
arr2d[:2, 2]

array([3, 6])

In [79]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

# Boolean Indexing

